name: BiocCheck

on:
  push:
    branches: [devel, modernize]
  pull_request:
    branches: [devel]

jobs:
  bioc-check:
    runs-on: ubuntu-latest
    container: bioconductor/bioconductor_docker:devel

    steps:
      - uses: actions/checkout@v4

      - name: Install package deps
        run: |
          BiocManager::install(ask = FALSE, update = FALSE)
          BiocManager::install("BiocCheck", ask = FALSE, update = FALSE)
        shell: Rscript {0}

      - name: Run BiocCheck
        run: |
          BiocCheck::BiocCheck(".", `quit-with-status` = TRUE,
                               `no-check-formatting` = FALSE)
        shell: Rscript {0}
